
#這些是受支援的融資模式平臺  github：#替換為hcj
最多4個啟用GitHub贊助商的使用者名稱，例如，[user1，user2] patreon：#替換為單個Patreon使用者名稱 open_collective：#替換為單個Open Collective使用者名稱 ko_fi：#替換為單個Ko-fi使用者名稱 tidelift：#替換為單個Tidelift平臺名稱/包裝名稱，例如npm/babel community_bridge：#替換為單個社群橋接專案名稱，例如雲基金會 liberapay：#替換為單個Liberapay使用者名稱 issuehunt：#替換為單個IssueHunt使用者名稱 otechie：#替換為單個Otechie使用者名稱 lfx_crowdfunding：#替換為單個LFX眾籌專案名稱，例如雲基金會 自定義：#替換為最多4個自定義贊助URL，例如，['link1'，'link2']
